name: General
description: Laporkan hal apa yang Anda temukan
labels: 'C: Native'
body:
  - type: input
    attributes:
      label: Sample URL
      placeholder: https://example.com
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Ad Blocker
      description: Produk ad blocker apa yang Anda gunakan?
      options:
        - AdGuard
        - uBlock Origin
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Ad Blocker
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: AdGuard
        - label: uBlock Origin
      required: true
  - type: textarea
    attributes:
      label: Keterangan
      description: Berikan penjelasan rinci.
    validations:
      required: true
