name: General
description: Laporkan hal apa yang Anda temukan
labels: 'C: Native'
body:
  - type: input
    attributes:
      label: Sample URL
      placeholder: https://example.com
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Ad Blocker
      description: What version of our software are you running?
      options:
        - AdGuard
        - uBlock Origin
    validations:
      required: true
  - type: textarea
    attributes:
      label: Keterangan
      description: Berikan penjelasan rinci.
    validations:
      required: true
