name: General
description: Laporkan hal apa yang Anda temukan
labels: 'C: Native'
body:
  - type: input
    attributes:
      label: Sample URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: Keterangan
      description: Berikan penjelasan rinci.
    validations:
      required: true
