name: Problem
description: AdBlockID menyebabkan masalah, seperti salah blokir atau hal lainnya.
labels: 'C: Bug'
body:
  - type: input
    attributes:
      label: Sample URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: Keterangan
      description: Berikan penjelasan rinci dan sertakan screenshot.
    validations:
      required: true
