name: Problem
description: AdBlockID menyebabkan masalah, seperti salah blokir atau hal lainnya.
title: 'example.com'
labels: 'C: Bug'
body:
  - type: input
    attributes:
      label: Sample URL
      placeholder: https://example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: Keterangan
      description: Berikan penjelasan rinci dan sertakan screenshot.
      placeholder: |
        - Mohon jelaskan ke Kami sedetail dan sejelas mungkin apa yang sebenarnya terjadi.
        - Jika memungkinkan berikan gambar screenshot.
        - Terkadang hal yang Anda laporkan muncul ketika [...]. Mohon jelaskan hal yang memicunya.
        - Berikan detail tentang ad blocker apa yang Anda gunakan dan filter apa saja yang gunakan.
        ...
    validations:
      required: true
