blank_issues_enabled: false
contact_links:
  - name: Pertanyaan Dukungan & Lainnya
    url: https://github.com/realodix/AdBlockID/discussions
    about: 'Jika Anda memiliki pertanyaan atau membutuhkan bantuan, klik:'
